apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-scanner
spec:
  selector:
    matchLabels:
      app: projects-scanner
  template:
    metadata:
      labels:
        app: projects-scanner
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-serviceaccount-key
      containers:
      - name: projects-scanner
        image: eu.gcr.io/bu-fyp-s5008913/projects-scanner@sha256:4114761eb891a7ac75f729703e39f53641fb3ee9d39945e4783546dea9148af6
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: RUN_DELAY_SECONDS
          valueFrom:
            configMapKeyRef:
              key: RUN_DELAY_SECONDS
              name: projects-scanner-config-1igv
        - name: PUBSUB_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              key: PUBSUB_TOPIC_NAME
              name: projects-scanner-config-1igv
        - name: API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: API_ENDPOINT
              name: projects-scanner-config-1igv
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              key: API_KEY
              name: projects-scanner-config-1igv
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json